spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BMS
    username: root
    password: 123456
  jpa:
    show-sql: false

  #静态资源
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static



